## 토이 데이터
- 머신러닝을 연습하거나 개념을 설명할 때 유용한 소규모 데이터셋
- 이 데이터들은 기본적으로 사이킷런에 내장되어 있어서 별도의 다운로드 없이 바로 사용할 수 있음

### 데이터셋 종류

| 데이터셋 | 문제 유형 | 특징 개수 | 샘플 수 | 설명 |
|---|---|---|---|---|
| `load_iris()` | 분류 | 4 | 150 | 붓꽃 품종 분류 |
| `load_digits()` | 분류 | 64 | 1797 | 손글씨 숫자 분류 |
| `load_wine()` | 분류 | 13 | 178 | 와인 종류 분류 |
| `load_breast_cancer()` | 분류 | 30 | 569 | 유방암 진단 |
| `fetch_california_housing()` | 회귀 | 8 | 20640 | 캘리포니아 주택 가격 예측 |
| `make_classification()` | 분류 | 사용자가 설정 | 사용자가 설정 | 임의 분류 데이터 생성 |
| `make_regression()` | 회귀 | 사용자가 설정 | 사용자가 설정 | 임의 회귀 데이터 생성 |
| `make_blobs()` | 군집 | 사용자가 설정 | 사용자가 설정 | 군집 데이터 생성 |


# 다룰 내용

- sklearn에서 제공하는 토이 데이터가 무엇인지, 어떻게 활용하는지 살펴보자.

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format='retina'

- load_iris() 함수로 붓꽃 품종 관련 데이터를 가져올 수 있다.

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

- DESCR 속성에 데이터에 대한 상세한 설명이 포함되어 있다.

In [3]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

- feature_names 속성에 독립변수들 이름이 포함되어 있다.
- data 속성에 독립변수들 값이 포함되어 있다.

In [6]:
print(iris.feature_names)
print(iris.data[:10])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


- target_names 속성에 종속변수 이름이 포함되어 있다.
- target 속성에 종속변수 값이 포함되어 있다.

In [7]:
print(iris.target_names)
print(iris.target[:10])

['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0]


- 위 정보들을 활용해 데이터프레임을 만들 수 있다.

In [8]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [9]:
# 변수 이름 변경
df.columns = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']

# 확인
df.head()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


- 데이터프레임에 종속변수, 즉 target이 되는 Species 변수를 추가한다.

In [10]:
df['Species'] = iris.target

df.head()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


- Species 변수의 값을 품종 이름으로 변경하면 우리가 아는 Iris 데이터프레임이 된다.

In [12]:
df['Species'].replace([0,1,2], iris.target_names, inplace=True)

df.head()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


- Iris 데이터는 품종별로 50씩의 관측치를 갖는다.

In [13]:
df['Species'].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64