# [실습] 배열 다루기


1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [ ]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
np_arr = np.array([[  1,  2,  3],
                   [  4,  5,  6],
                   [  7,  8,  9],
                   [ 10, 11, 12]])

# 확인
print(np_arr)

3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [ ]:
# 배열 크기 확인
np_arr.shape

4) np_arr 배열을 아래 주어진 3 X 4 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [ ]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# 형태 변경
np_02 = np_arr.reshape(3, -1)

# 확인
print(np_02)

5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

In [ ]:
# [7 8 9] 조회
print(np_arr[2])

6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

In [ ]:
# 10 곱하기
print(np_arr * 10)

7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.

In [ ]:
print(np_arr[np_arr > 7])

8) 위의 실습에서 선택된 요소들의 값을 모두 2배로 만드세요.

In [ ]:
# 조회 결과에 대한 연산
np_arr[np_arr > 7] = np_arr[np_arr > 7] * 2

9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

In [ ]:
# 원본 배열 확인
print(np_arr)

10) np_arr 배열의 요소들 중에서 홀수인 요소만 조회해서 a 라는 리스트로 선언하고 확인하세요.

In [ ]:
# 리스트로 변환
a = list(np_arr[np_arr % 2 == 1])

# 확인
print(a)